server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Necessário para rotas do React funcionarem corretamente
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para a API
    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Opcional: Para rota de uploads sendo servida pelo backend diretamente ou pelo docker-compose backend
    location /uploads/ {
        proxy_pass http://backend:3000/uploads/;
    }
}
